# -*- coding: utf-8 -*-
"""Naive_bayes_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSZ0haPLRbkMij2vYK7FUuwxstcSlRJE
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer as cv
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report

texts =[
    "This movie is good!!",
    "Worst movie ever",
    "Amazing direction",
    "I enjoyed it",
    "Movie is not so good but I like casting",
    "songs are really nice",
    "I don't recommend this movie to anyone",
    "not upto the hype",
    "Average",
    "must watch",
]
labels = ["positive",
          "negative",
          "positive",
          "positive",
          "positive",
          "negative",    #fixed here
          "positive",
          "negative",
          "negative",
          "positive",
          "positive"]

import string
def preprocess(text):
  text=text.lower()
  text=text.translate(str.maketrans('','',string.punctuation))
  return text
texts=[preprocess(t) for t in texts]

X_train , X_test , Y_train , Y_test = train_test_split(
  texts,labels,test_size=0.3, random_state =65
)

vector=cv()
X_train_vec=vector.fit_transform(X_train)
X_test_vec=vector.transform(X_test)

model1=MultinomialNB()

model1.fit(X_train_vec,Y_train)

y_predc=model1.predict(X_test_vec)
print("Prediction : ",y_predc)

print("Accuracy : ",accuracy_score(Y_test,y_predc))
print(classification_report(Y_test,y_predc))

new_text=input("Enter your feedback : ").strip()
new_text=preprocess(new_text)
new_text_vec=vector.transform([new_text])
print("Prediction : ",model1.predict(new_text_vec))
